# Writes build_version.h (the library's version and, when the source tree
# is a git checkout, its commit). Run at build time, not configure time,
# so a rebuild after a commit records the new commit. The file is only
# rewritten when its contents change, so an unchanged tree does not
# recompile anything.
#
#   cmake -DVERSION=<v> -DSOURCE_DIR=<repo> -DOUTPUT=<file> -P WriteVersion.cmake

set(_commit "")
find_package(Git QUIET)
if(GIT_FOUND)
    # Only the source tree's own checkout: a tree exported into some other
    # repository's directory must not record that repository's commit.
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --show-toplevel
        OUTPUT_VARIABLE _top
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
endif()
if(_top)
    get_filename_component(_top "${_top}" REALPATH)
    get_filename_component(_src "${SOURCE_DIR}" REALPATH)
endif()
if(_top AND _top STREQUAL _src)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=12 HEAD
        OUTPUT_VARIABLE _commit
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _rc
        ERROR_QUIET)
    if(NOT _rc EQUAL 0)
        set(_commit "")
    else()
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain --untracked-files=no
            OUTPUT_VARIABLE _dirty
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET)
        if(_dirty)
            string(APPEND _commit "-dirty")
        endif()
    endif()
endif()

set(_text "// Generated by cmake/WriteVersion.cmake. Do not edit.
#pragma once
#define CUPTI_PROFILER_VERSION \"${VERSION}\"
#define CUPTI_PROFILER_GIT_COMMIT \"${_commit}\"
")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" _old)
    if(_old STREQUAL _text)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${_text}")
